on:
  push:
    branches: [ main ]
jobs:
  build-instructions-pdf:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build PDF
        run:  make -C instructions ZEPHYRVERSION=4.2.0 SDKVERSION=0.17.2 MCU=STM32F429ZI BOARD=stm32f429i\\_disc1 IMAGENAME=zephyr\\_v\\zephyrversion{}\\_stm32
      - uses: actions/upload-artifact@v4
        with:
          name: instructions-for-students
          path: instructions/build/zephyr_container.pdf
  release-instructions-pdf:
    needs: build-instructions-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: instructions-for-students
          path: .
      - name: Recreate release
        run: |
          gh release delete latest --cleanup-tag --yes --repo $GITHUB_REPOSITORY || true
          gh release create latest --latest --title "Instructions for Students" --repo $GITHUB_REPOSITORY "zephyr_container.pdf"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
